
spring:
  servlet:
    #configuiring multipart file upload
    multipart:
      enabled: true
      max-file-size: 40960
      file-size-threshold: 4
    #configuiring database
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: 123@Pakistan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  #spring batch configuration
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always