
spring:
  servlet:
    #configuiring multipart file upload
    multipart:
      enabled: true
<<<<<<< HEAD
      max-file-size: 40960
=======
      max-file-size: 200
>>>>>>> 8d9d15d4dfa3119c9bc50c2519de168900b042b9
      file-size-threshold: 4
    #configuiring database
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: 123@Pakistan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
<<<<<<< HEAD
    open-in-view: false
  #spring batch configuration
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
=======
>>>>>>> 8d9d15d4dfa3119c9bc50c2519de168900b042b9
